React 완벽 가이드 - 섹션 26: 리액트 앱 테스트(단위 테스트) #2 jest test setting
svg, css import 문제
- https://stackoverflow.com/questions/39418555/syntaxerror-with-jest-and-react-and-importing-css-files

TypeError: expect(...).toBeInTheDocument is not a function 문제
- https://stackoverflow.com/questions/56547215/react-testing-library-why-is-tobeinthedocument-not-a-function